name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
        
    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ec2-18-226-165-114.us-east-2.compute.amazonaws.com
        EC2_USERNAME: ubuntu
      run: |
        # Setup SSH key with proper permissions
        mkdir -p ~/.ssh
        echo "$EC2_SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add host to known_hosts
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        
        # Copy JAR to EC2
        scp -i ~/.ssh/deploy_key target/kura-*.jar $EC2_USERNAME@$EC2_HOST:~/app.jar
        
        # Deploy application
        ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST '
          # Kill existing application if running
          pid=$(pgrep -f app.jar) && kill -9 $pid || true
          
          # Start the application with proper memory settings
          nohup java -Xmx512m -jar app.jar > app.log 2>&1 &
          
          # Wait and verify
          sleep 15
          if pgrep -f app.jar > /dev/null; then
            echo "Application deployed successfully"
          else
            echo "Application failed to start" && exit 1
          fi
        '


